[build]
  # 发布目录（静态文件所在目录）
  publish = "."
  
  # 构建命令（如果需要构建）
  # command = "npm run build"
  
  # 环境变量
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

[build.processing]
  # 启用HTML处理
  html = true
  # 启用CSS处理
  css = true
  # 启用JS处理
  js = true
  # 启用图片处理
  images = true

[build.processing.html]
  # HTML压缩
  pretty_urls = true

[build.processing.css]
  # CSS压缩
  bundle = true
  # 自动添加浏览器前缀
  autoprefixer = true

[build.processing.js]
  # JS压缩
  bundle = true
  # 代码分割
  split_bundles = true

[build.processing.images]
  # 图片优化
  compress = true

# 重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 缓存控制
    Cache-Control = "public, max-age=31536000"
    
    # 内容安全策略
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; font-src 'self' data:; connect-src 'self' https://api.qrserver.com https://appapi.simyo.nl https://api.giffgaff.com https://id.giffgaff.com https://publicapi.giffgaff.com; img-src 'self' data: https:; frame-src 'none';"

# 特定文件的头部设置
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 函数配置（如果需要）
[functions]
  directory = "netlify/functions"