[build]
  # 构建命令
  command = "npm install"
  # 发布目录
  publish = "."
  # Functions目录
  functions = "netlify/functions"
  
# 重定向和重写规则
[[redirects]]
  # Giffgaff eSIM页面（安全版本）
  from = "/giffgaff"
  to = "/src/secure/giffgaff-secured.html"
  status = 200

[[redirects]]
  # Giffgaff eSIM页面（传统版本，仅开发环境）
  from = "/giffgaff-legacy"
  to = "/src/giffgaff/giffgaff_complete_esim.html"
  status = 200
  condition = "Role=developer"

[[redirects]]
  # Simyo eSIM页面
  from = "/simyo"
  to = "/src/simyo/simyo_complete_esim.html"
  status = 200



[[redirects]]
  # 根路径重定向到选择页面
  from = "/"
  to = "/index.html"
  status = 200

# API代理重定向（用于解决CORS问题）
[[redirects]]
  from = "/api/simyo/*"
  to = "https://appapi.simyo.nl/simyoapi/api/v1/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "appapi.simyo.nl"}

[[redirects]]
  from = "/api/giffgaff/*"
  to = "https://api.giffgaff.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "api.giffgaff.com"}

[[redirects]]
  from = "/api/giffgaff-id/*"
  to = "https://id.giffgaff.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "id.giffgaff.com"}

[[redirects]]
  from = "/api/giffgaff-public/*"
  to = "https://publicapi.giffgaff.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "publicapi.giffgaff.com"}

# 处理SPA路由（如果需要）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# 企业级安全头部
[[headers]]
  for = "/*"
  [headers.values]
    # 基础安全头部
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 强化的内容安全策略
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self'; font-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # HSTS强制HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # 权限策略
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # 防止MIME类型嗅探
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"
    
    # 缓存控制
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# 静态资源安全头部
[[headers]]
  for = "/src/secure/*"
  [headers.values]
    # 额外的安全措施用于敏感页面
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet, noimageindex"
    X-Frame-Options = "DENY"
    Cache-Control = "no-cache, no-store, must-revalidate, private"
    
# API端点安全头部
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-Session-ID, X-Timestamp, X-Signature"